[project]
name = "example-Snakemake_Pipeline"
version = "0.1.0"
description = "Add a short description here"
authors = ["Jermiah Joseph <jermiahjoseph98@gmail.com>"]
channels = ["conda-forge", "bioconda"]
platforms = ["osx-arm64"]

[tasks]

[dependencies]
snakemake = "==7.32.4"
