name: example-Snakemake_Pipeline
description: This is an example pipeline for Snakemake. Uses some data from PRISM. 
url: https://www.theprismlab.org.

metadata:
  sampleMetadata: 
    description: Contains the meta data about the cell lines screened in the assay.
    url: https://ndownloader.figshare.com/files/41408658
  treatmentMetadata:
    description: Contains the meta data about the treatment/perturbation in each well of each plate.
    url: https://ndownloader.figshare.com/files/41408649
  genomeMetadata:
    description: Contains the meta data about the genome build used in the assay.
    url: ccleparams/references_gtex_gencode.v29.GRCh38.ERCC.genes.collapsed_only.gtf

treatmentResponse:
  description: Contains the response of each cell line to each treatment.
  url: https://ndownloader.figshare.com/files/41408703

molecularProfiles:
  rnaseq:
    description: RNA-seq gene expression data. TPM values are log2 transformed.
    tool: RSEM
    url: https://data.broadinstitute.org/ccle/CCLE_RNAseq_rsem_genes_tpm_20180929.txt.gz
    